/*
Below is the fourth in five queries that extract various aspects of user 
behavior that mimicks typical bot-like behavior on SNS services like instagram. 
Specifically, the query below outputs each user's total followers, the site
average total followers, users' difference from site average, each user's total
following, site average total following, the difference from site average, 
following-to-followers ratio, comparison against the site average, and based on
the criteria of the case statement below, the probabiliy that a given users is 
a bot: "high", "moderate", or "uncertain".

The reasoning behind this query was that bots typically follow an inordinate
amount of users, yet have a very small following. 
*/



SELECT user_id, 
SUM(number_followers) AS total_followers, 
ROUND(AVG(SUM(number_followers)) OVER(), 2) AS site_AVG_total_followers,
SUM(number_followers) - ROUND(AVG(SUM(number_followers)) OVER(), 2) AS total_followers_diff_from_AVG,
SUM(number_following) AS total_following, -- the sum function is used because the union add the two subquerries togeth in rows, so e.g. you have user_id: 1, total_followers: 5, total_following: 0
ROUND(AVG(SUM(number_following)) OVER(), 2) AS site_AVG_total_following,
-- and then you'll have user_id: 1 again, but with number_of_followers: 0 and number_following: 4. these need to be combined/added and a GROUP BY or COUNT() won't do that, it has to be summed.
SUM(number_following) - ROUND(AVG(SUM(number_following)) OVER(), 2) AS total_following_diff_from_AVG,
ROUND((SUM(number_following))/(SUM(number_followers)), 2) AS following_followers_ratio, 
ROUND(AVG((SUM(number_following))/(SUM(number_followers))) OVER(), 2) AS site_AVG_following_followers_ratio,
ROUND((SUM(number_following))/(SUM(number_followers)) - AVG((SUM(number_following))/(SUM(number_followers))) OVER(), 2) AS 'following_followers_ratio_diff_from_AVG',
CASE 
WHEN ROUND((SUM(number_following))/(SUM(number_followers)), 2) > 5 THEN 'high' -- As mentioned above, the cutoffs would be more consistent with real-world number if they were around 100 and 25 for 'high' and 'moderate', but due to the limitations of the data, 5 and 2.5 were used to simply demonstrate the query.
WHEN ROUND((SUM(number_following))/(SUM(number_followers)), 2) > 2.5 THEN 'moderate'
ELSE 'uncertain'
END AS 'prob_user_is_robot'
FROM (
    -- Query for followers
    SELECT followee_id AS user_id, COUNT(follower_id) AS number_followers, 0 AS number_following -- 0 is placed here because this query is only retrieving the number of followers (can't do both in one query)
    FROM follows
    GROUP BY followee_id
    UNION
    -- Query for following
    SELECT follower_id AS user_id, 0 AS number_followers, COUNT(followee_id) AS number_following -- 0 is used because this query is only retrieving the number following (can't do both in one query)
    FROM follows
    GROUP BY follower_id
) AS subquery
GROUP BY user_id
ORDER BY prob_user_is_robot;



-- Below is a sample of the ouput from the top 10 rows:
/* 
*** Please note again that this is from simulated data, and this query in particular
shows more repeated data than the others.*** 
*/

+---------+-----------------+--------------------------+-------------------------------+-----------------+--------------------------+-------------------------------+---------------------------+------------------------------------+-----------------------------------------+--------------------+
| user_id | total_followers | site_AVG_total_followers | total_followers_diff_from_AVG | total_following | site_AVG_total_following | total_following_diff_from_AVG | following_followers_ratio | site_AVG_following_followers_ratio | following_followers_ratio_diff_from_AVG | prob_user_is_robot |
+---------+-----------------+--------------------------+-------------------------------+-----------------+--------------------------+-------------------------------+---------------------------+------------------------------------+-----------------------------------------+--------------------+
|     100 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      99 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      98 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      97 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      96 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      95 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      94 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      93 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      92 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      91 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      87 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      85 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      84 |              17 |                    48.59 |                        -31.59 |              99 |                    48.59 |                         50.41 |                      5.82 |                               1.72 |                                    4.10 | high               |
|      14 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      15 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      16 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      17 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      18 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      19 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      20 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      21 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      22 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      23 |              77 |                    48.59 |                         28.41 |               0 |                    48.59 |                        -48.59 |                      0.00 |                               1.72 |                                   -1.72 | uncertain          |
|      24 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      25 |              77 |                    48.59 |                         28.41 |               0 |                    48.59 |                        -48.59 |                      0.00 |                               1.72 |                                   -1.72 | uncertain          |
|      26 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      27 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      28 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      29 |              77 |                    48.59 |                         28.41 |               0 |                    48.59 |                        -48.59 |                      0.00 |                               1.72 |                                   -1.72 | uncertain          |
|      30 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      31 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      32 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      33 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      34 |              77 |                    48.59 |                         28.41 |               0 |                    48.59 |                        -48.59 |                      0.00 |                               1.72 |                                   -1.72 | uncertain          |
|      35 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      36 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      37 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      38 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      39 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      40 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      41 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      42 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      43 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      44 |              76 |                    48.59 |                         27.41 |              99 |                    48.59 |                         50.41 |                      1.30 |                               1.72 |                                   -0.42 | uncertain          |
|      45 |              77 |                    48.59 |                         28.41 |               0 |                    48.59 |                        -48.59 |                      0.00 |                               1.72 |                                   -1.72 | uncertain          |
|      46 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      47 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      48 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      49 |              79 |                    48.59 |                         30.41 |              17 |                    48.59 |                        -31.59 |                      0.22 |                               1.72 |                                   -1.51 | uncertain          |
|      50 |              54 |                    48.59 |                          5.41 |              49 |                    48.59 |                          0.41 |                      0.91 |                               1.72 |                                   -0.82 | uncertain          |
|       1 |              94 |                    48.59 |                         45.41 |              17 |                    48.59 |                        -31.59 |                      0.18 |                               1.72 |                                   -1.54 | uncertain          |
|      52 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      53 |              22 |                    48.59 |                        -26.59 |              15 |                    48.59 |                        -33.59 |                      0.68 |                               1.72 |                                   -1.04 | uncertain          |
|      54 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      55 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      56 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      57 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      58 |              23 |                    48.59 |                        -25.59 |              14 |                    48.59 |                        -34.59 |                      0.61 |                               1.72 |                                   -1.11 | uncertain          |
|      59 |              24 |                    48.59 |                        -24.59 |              13 |                    48.59 |                        -35.59 |                      0.54 |                               1.72 |                                   -1.18 | uncertain          |
|      60 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      61 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      62 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      63 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      64 |              25 |                    48.59 |                        -23.59 |              12 |                    48.59 |                        -36.59 |                      0.48 |                               1.72 |                                   -1.24 | uncertain          |
|      65 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      66 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      67 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      68 |              26 |                    48.59 |                        -22.59 |              11 |                    48.59 |                        -37.59 |                      0.42 |                               1.72 |                                   -1.30 | uncertain          |
|      69 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      70 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      71 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      72 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      73 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      74 |              27 |                    48.59 |                        -21.59 |              10 |                    48.59 |                        -38.59 |                      0.37 |                               1.72 |                                   -1.35 | uncertain          |
|      75 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      76 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      77 |              28 |                    48.59 |                        -20.59 |               9 |                    48.59 |                        -39.59 |                      0.32 |                               1.72 |                                   -1.40 | uncertain          |
|      78 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      79 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      80 |              29 |                    48.59 |                        -19.59 |               8 |                    48.59 |                        -40.59 |                      0.28 |                               1.72 |                                   -1.45 | uncertain          |
|      81 |              30 |                    48.59 |                        -18.59 |               7 |                    48.59 |                        -41.59 |                      0.23 |                               1.72 |                                   -1.49 | uncertain          |
|      82 |              18 |                    48.59 |                        -30.59 |              49 |                    48.59 |                          0.41 |                      2.72 |                               1.72 |                                    1.00 | uncertain          |
|      83 |              32 |                    48.59 |                        -16.59 |               5 |                    48.59 |                        -43.59 |                      0.16 |                               1.72 |                                   -1.57 | uncertain          |
|      13 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      12 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      86 |              33 |                    48.59 |                        -15.59 |               4 |                    48.59 |                        -44.59 |                      0.12 |                               1.72 |                                   -1.60 | uncertain          |
|      11 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|      88 |              35 |                    48.59 |                        -13.59 |               2 |                    48.59 |                        -46.59 |                      0.06 |                               1.72 |                                   -1.67 | uncertain          |
|      89 |              34 |                    48.59 |                        -14.59 |               3 |                    48.59 |                        -45.59 |                      0.09 |                               1.72 |                                   -1.63 | uncertain          |
|      90 |              35 |                    48.59 |                        -13.59 |              17 |                    48.59 |                        -31.59 |                      0.49 |                               1.72 |                                   -1.24 | uncertain          |
|      10 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|       9 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|       8 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|       7 |              90 |                    48.59 |                         41.41 |               6 |                    48.59 |                        -42.59 |                      0.07 |                               1.72 |                                   -1.66 | uncertain          |
|       6 |              76 |                    48.59 |                         27.41 |              49 |                    48.59 |                          0.41 |                      0.64 |                               1.72 |                                   -1.08 | uncertain          |
|       5 |              76 |                    48.59 |                         27.41 |              99 |                    48.59 |                         50.41 |                      1.30 |                               1.72 |                                   -0.42 | uncertain          |
|       4 |              76 |                    48.59 |                         27.41 |              99 |                    48.59 |                         50.41 |                      1.30 |                               1.72 |                                   -0.42 | uncertain          |
|       3 |              76 |                    48.59 |                         27.41 |              99 |                    48.59 |                         50.41 |                      1.30 |                               1.72 |                                   -0.42 | uncertain          |
|       2 |              76 |                    48.59 |                         27.41 |              99 |                    48.59 |                         50.41 |                      1.30 |                               1.72 |                                   -0.42 | uncertain          |
|      51 |              21 |                    48.59 |                        -27.59 |              16 |                    48.59 |                        -32.59 |                      0.76 |                               1.72 |                                   -0.96 | uncertain          |
+---------+-----------------+--------------------------+-------------------------------+-----------------+--------------------------+-------------------------------+---------------------------+------------------------------------+-----------------------------------------+--------------------+